server:
  port: 9003

spring:
  profiles:
    active: local
  application:
    name: ticketing-system-order${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:${shardingsphere.config-location:classpath:shardingsphere-config.yaml}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
      username: ${nacos.username}
      password: ${nacos.password}
    sentinel:
      transport:
        dashboard: ${sentinel.dashboard}
        port: 8719
  data:
    redis:
      host: ${redis.host}
      port: 16379
      password: ${redis.password}

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safe-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

rocketmq:
  name-server: ${rocketmq.name-server}
  producer:
    group: ticketing-system_order${unique-name:}-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
