server:
  port: 9000

spring:
  application:
    name: ticketing-system-gateway${unique-name:}-service
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
    gateway:
      httpclient:
        response-timeout: 300s
      routes:
        - id: ticketing-system-user-service
          uri: lb://ticketing-system-user${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion
        - id: ticketing-system-ticket-service
          uri: lb://ticketing-system-ticket${unique-name:}-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket-service/ticket/purchase
                  - /api/ticket-service/ticket/pay/query
                  - /api/ticket-service/ticket/cancel
        - id: ticketing-system-pay-service
          uri: lb://ticketing-system-pay${unique-name:}-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**
        - id: ticketing-system-order-service
          uri: lb://ticketing-system-order${unique-name:}-service/api/order-service/**
          predicates:
            - Path=/api/order-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order-service/order/ticket/query
                  - /api/order-service/order/ticket/page
                  - /api/order-service/order/ticket/self/page
        - id: ticketing-system-ai-service
          uri: lb://ticketing-system-ai${unique-name:}-service/api/ai-service/**
          predicates:
            - Path=/api/ai-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ai-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
